### ISSUE TITLE
GWT incompatibility

### ISSUE THREAD

**Issue by BenMcLean** [SudoPlayGames/Joise#10] opened 2017-01-02 07:42 UTC
I'm trying to use Joise with the GWT backend for libGDX and apparently it has some incompatibilities. I [forked](https://github.com/BenMcLean/Joise/) to work on the problem, so hopefully there will be a PR from me to fix this issue soon.

I have listed the build errors I am getting which I believe indicate incompatibilities with GWT [in this comment here](https://github.com/BenMcLean/Joise/commit/19fc6270ef47eb9db8a813d554d222f3401d3ac8#commitcomment-20337168).

**Comment by codetaylor** [comment] 2017-01-02 17:51
So it looks like the problem is that Joise uses classes from java.lang and java.util that aren't implemented in the subset of Java that GWT supports. Is that right?

**Comment by codetaylor** [comment] 2017-01-02 18:00
Specifically GWT does not implement the classes:

- java.util.concurrent.atomic.AtomicInteger
- java.lang.reflect.Method
- java.lang.ThreadLocal

... and does not provide these methods on the Class object:

- isInstance(Object)
- cast(Object)
- getMethod(String, Class)

Did I miss anything?

**Comment by BenMcLean** [comment] 2017-01-02 19:53
I believe that is correct. In [my fork](https://github.com/BenMcLean/Joise/commits/master), I've been working to reduce or replace references to these things in the code. But I'm starting to hit a wall when it comes to method reflection.

**Comment by BenMcLean** [comment] 2017-01-02 19:53
Here is a [relevant article](https://www.securecoding.cert.org/confluence/display/java/SEC05-J.+Do+not+use+reflection+to+increase+accessibility+of+classes,+methods,+or+fields)

**Comment by BenMcLean** [comment] 2017-01-02 19:55
What libGDX does is [emulate reflection](https://github.com/libgdx/libgdx/wiki/Reflection) with [this package](https://github.com/libgdx/libgdx/tree/master/gdx/src/com/badlogic/gdx/utils/reflect).

**Comment by BenMcLean** [comment] 2017-01-02 20:09
BTW, in addition to finding a way around using the things you listed, GWT will also require adding [this XML file](https://github.com/BenMcLean/Joise/blob/master/src/joise.gwt.xml)

**Comment by codetaylor** [comment] 2017-01-03 05:48
I'm not actually using reflection to increase the accessibility of the Module sub-classes, as all of the methods referenced are public anyway. It looks more like I was trying to encapsulate the act of reading mapped properties into the module in a concise fashion.

So that I could do something like this:
```
readScalar("high", "setHighSource", props, map);
```

... instead of something like this:
```
this.setHighSource(readScalar("high", props, map));
```

The problem being, for this specific example, `readScalar()`, would have two different return types. I think that was what I was trying to work around by using reflection.

I can fix this tomorrow and remove all of the reflection. :)

**Comment by BenMcLean** [comment] 2017-01-03 07:01
> I'm not actually using reflection to increase the accessibility of the Module sub-classes,

OK, maybe that article wasn't so relevant after all. I thought it was saying ((Don't use reflection) to increase accessibility)) but I guess what it's really saying is (Don't (use reflection to increase accessibility))

> I will fix this tomorrow and remove all of the reflection. :)

Oh wow, if you could fix this so that it works with GWT, I would appreciate that so much. :) I thought I could make the changes myself but I got a little lost working on it today.

**Comment by codetaylor** [comment] 2017-01-03 16:40
Got a start on it: 17305cba8720a4c1bb3d29339018c33aaba446bf

**Comment by codetaylor** [comment] 2017-01-03 16:49
Remaining:

- Joise.java `[ERROR] Line 111: The method forName(String) is undefined for the type Class`
- Noise.java `[ERROR] Line 67: No source code is available for type java.lang.ThreadLocal`

**Comment by BenMcLean** [comment] 2017-01-03 17:14
Wow! I'm excited. :)

**Comment by codetaylor** [comment] 2017-01-03 17:17
Fixed Joise.java `[ERROR] Line 111`: 973882f79028ab058f96ad430fedceea09bae04c

I borrowed some of the work you did for this one @BenMcLean , I hope that's ok. I credited you in a comment in the file.

**Comment by codetaylor** [comment] 2017-01-03 17:23
Remaining:

- Noise.java `[ERROR] Line 67: No source code is available for type java.lang.ThreadLocal`
- Module.java `[ERROR] Line 75: No source code is available for type java.util.concurrent.atomic.AtomicInteger` (forgot this one earlier)

**Comment by codetaylor** [comment] 2017-01-03 17:36
Fixed Module.java `[ERROR] Line 75`: 7b5368cf76bea6afda137837203a2a6774c6516c

I simply changed the AtomicInteger to an int because I can't reliably make the claim that this library is thread safe without more extensive testing. See #8 .

Moving on to the remaining:
 - Noise.java `[ERROR] Line 67: No source code is available for type java.lang.ThreadLocal`

**Comment by codetaylor** [comment] 2017-01-03 18:17
This last one is more involved and I've unfortunately run out of time for this today. I'm going to leave some thoughts here so I can quickly pick up again tomorrow.

The Noise class is essentially static, containing no state with the exception of the ByteBuffers used to store temporary values for hashing. The reason that the buffers were made ThreadLocal is to ensure that if the Noise class's static methods are accessed from different threads, none of the values get mixed up, concurrently accessed, etc... I did make the claim that this library is not thread safe, however in #8 I recommend building an identical module chain in each thread. If that advice was followed, then removing the ThreadLocal will remove the possibility of that solution.

It looks like the only two classes that reference the Noise class, outside of the Noise class itself, are the ModuleBasisFunction class and the ModuleCellGen class. It may be possible to redesign the Noise class to contain state (ie. buffers) and provide the aforementioned module classes each with an instance of the Noise class.

Then, if identical module chains were created in two different threads, each thread would have its own instances of the Noise (with state) object.

I also feel that the change to the AtomicInteger in the Module class warrants further investigation.

**Comment by BenMcLean** [comment] 2017-01-03 22:22
OK, thanks so much for working on this. I hope it get solved soon!

I sent in a [pull request to add the XML](https://github.com/SudoPlayGames/Joise/pull/11).

**Comment by codetaylor** [comment] 2017-01-04 16:56
You're welcome, @BenMcLean and thanks for the PR. I've got a handle on how I'm going to fix the ThreadLocal. It turns out that GWT doesn't support the ByteBuffer class either, or any of java.nio for that matter. So I'm going from the ground up on this one, starting with replacing the small subset of the ByteBuffer functionality that I was using, specifically creating the byte arrays for hashing. The upside to this is it may actually increase performance in addition to making it compile with GWT. This will take more time than I initially anticipated and I thank you for your patience. :)

Remaining:
- Create util class to fill byte arrays + tests
- Factor out static instances of noise interfaces
- Replace references to the static instances of noise interfaces
- Investigate repercussions of removing the AtomicInteger in the Module class

**Comment by BenMcLean** [comment] 2017-01-04 17:02
You could just add in classes other people have written which emulate the functionality of the missing classes. [guava has AtomicInteger](https://github.com/google/guava/blob/master/guava-gwt/src-super/java/util/super/java/util/concurrent/atomic/AtomicInteger.java) (not sure how thread safe it actually is) and [gwt-nyartoolkit has ByteBuffer](https://github.com/abmancini/gwt-nyartoolkit/blob/master/GWT-NyARToolKit/src/com/jooink/gwt/nyartoolkit/jre/java/nio/ByteBuffer.java). Not sure what to do about ThreadLocal though.

**Comment by codetaylor** [comment] 2017-01-04 17:22
Remaining:

- ~~Create util class to fill byte arrays + tests~~ 5325f6bc41b7c3cb063f1509836ae174d6bfc0b7
- Factor out static instances of noise interfaces
- Replace references to the static instances of noise interfaces
- Investigate repercussions of removing the AtomicInteger in the Module class

**Comment by codetaylor** [comment] 2017-01-04 20:17
Just one thing left now, but I don't have any more time today.

@BenMcLean I looked at several GWT friendly versions of ByteBuffer, ThreadLocal, and AtomicInteger. Instead of replacing the ByteBuffer class with an equally bloated emulation class, I decided to bypass the ByteBuffer entirely. The only reason that I was using a ByteBuffer was to convert ints, doubles and longs into byte arrays, which can be done without the use of a ByteBuffer, possibly increasing performance. The ThreadLocal and AtomicInteger replacements are designed to have all of the methods of the originals, but none of the multi-threaded functionality that I chose them for.

My goal with these changes is to eliminate usage of classes and methods not supported by GWT while not changing the existing behavior of the library. At the end of the day, my priority is that the library compiles and behaves as expected (read: as it has in the past) with Java. Unfortunately, using drop-in classes that reduce or alter functionality would compromise that priority.

As it stands now, the `develop` branch should compile with GWT, given that there aren't any new surprise errors. Give it a go and let me know how it works. :)

**Comment by BenMcLean** [comment] 2017-01-04 20:57
Oops, I guess this should actually be marked "Resolved" before "Closed"

**Comment by codetaylor** [comment] 2017-01-05 17:38
I'm glad it works! I think it's OK to close this - I usually close the issue when it's resolved, one way or another. :)

**Closed by codetaylor** 2017-01-05 17:38 UTC

**Comment by codetaylor** [comment] 2017-01-06 17:50
You're absolutely right, see #13 .
